import type { Route } from './types';

export const ROUTES: Route[] = [
  // ── Easy ────────────────────────────────────────────────────────────────────
  {
    id: 'city_loop',
    name: 'City Loop',
    description: 'A flat urban circuit through downtown and the suburbs. Great for new drivers.',
    distanceMi: 40,
    difficulty: 'Easy',
    reward: 200,
    unlockAfterTrips: 0,
    terrain: [
      { distanceMi: 0,  elevationFt: 100, speedLimitMph: 35 },
      { distanceMi: 5,  elevationFt: 115, speedLimitMph: 35 },
      { distanceMi: 10, elevationFt: 105, speedLimitMph: 45 },
      { distanceMi: 20, elevationFt: 110, speedLimitMph: 55 },
      { distanceMi: 30, elevationFt: 95,  speedLimitMph: 45 },
      { distanceMi: 40, elevationFt: 100, speedLimitMph: 35 },
    ],
    chargers: [
      { id: 'city_l2_a', name: 'Mall Level 2', network: 'ChargePoint', positionMi: 15, maxKw: 19.2, pricePerKwh: 0.12 },
      { id: 'city_dc_a', name: 'Downtown DC Fast', network: 'Electrify America', positionMi: 28, maxKw: 150, pricePerKwh: 0.28 },
    ],
  },
  {
    id: 'coastal_cruise',
    name: 'Coastal Cruise',
    description: 'Gentle rolling hills along the shoreline with ocean views.',
    distanceMi: 80,
    difficulty: 'Easy',
    reward: 350,
    unlockAfterTrips: 1,
    terrain: [
      { distanceMi: 0,  elevationFt: 50,  speedLimitMph: 55 },
      { distanceMi: 10, elevationFt: 200, speedLimitMph: 55 },
      { distanceMi: 20, elevationFt: 80,  speedLimitMph: 65 },
      { distanceMi: 35, elevationFt: 250, speedLimitMph: 55 },
      { distanceMi: 50, elevationFt: 60,  speedLimitMph: 65 },
      { distanceMi: 65, elevationFt: 180, speedLimitMph: 55 },
      { distanceMi: 80, elevationFt: 50,  speedLimitMph: 55 },
    ],
    chargers: [
      { id: 'coast_sc_a', name: 'Seaside Supercharger', network: 'Tesla', positionMi: 22, maxKw: 250, pricePerKwh: 0.25 },
      { id: 'coast_dc_a', name: 'Harbor DC Fast',       network: 'EVgo',  positionMi: 55, maxKw: 100, pricePerKwh: 0.30 },
    ],
  },

  // ── Medium ───────────────────────────────────────────────────────────────────
  {
    id: 'valley_run',
    name: 'Valley Run',
    description: 'Wind through a river valley with moderate elevation changes and two charger stops.',
    distanceMi: 130,
    difficulty: 'Medium',
    reward: 600,
    unlockAfterTrips: 3,
    terrain: [
      { distanceMi: 0,   elevationFt: 500,  speedLimitMph: 65 },
      { distanceMi: 15,  elevationFt: 800,  speedLimitMph: 65 },
      { distanceMi: 30,  elevationFt: 300,  speedLimitMph: 70 },
      { distanceMi: 50,  elevationFt: 1100, speedLimitMph: 65 },
      { distanceMi: 70,  elevationFt: 400,  speedLimitMph: 70 },
      { distanceMi: 90,  elevationFt: 900,  speedLimitMph: 65 },
      { distanceMi: 110, elevationFt: 500,  speedLimitMph: 70 },
      { distanceMi: 130, elevationFt: 500,  speedLimitMph: 65 },
    ],
    chargers: [
      { id: 'valley_sc_a',  name: 'Ridgeline Supercharger',  network: 'Tesla',             positionMi: 35,  maxKw: 250, pricePerKwh: 0.25 },
      { id: 'valley_ea_a',  name: 'Valley Crossing EA',       network: 'Electrify America', positionMi: 72,  maxKw: 350, pricePerKwh: 0.27 },
      { id: 'valley_l2_a',  name: 'Riverside Level 2',        network: 'ChargePoint',       positionMi: 105, maxKw: 19.2,pricePerKwh: 0.14 },
    ],
  },
  {
    id: 'interstate_haul',
    name: 'Interstate Haul',
    description: 'Long highway stretch at high speed. Efficiency matters most here.',
    distanceMi: 220,
    difficulty: 'Medium',
    reward: 900,
    unlockAfterTrips: 5,
    terrain: [
      { distanceMi: 0,   elevationFt: 800,  speedLimitMph: 75 },
      { distanceMi: 40,  elevationFt: 1200, speedLimitMph: 75 },
      { distanceMi: 80,  elevationFt: 600,  speedLimitMph: 80 },
      { distanceMi: 120, elevationFt: 1400, speedLimitMph: 75 },
      { distanceMi: 160, elevationFt: 800,  speedLimitMph: 80 },
      { distanceMi: 200, elevationFt: 1100, speedLimitMph: 75 },
      { distanceMi: 220, elevationFt: 900,  speedLimitMph: 75 },
    ],
    chargers: [
      { id: 'inter_sc_a', name: 'Highway 40 Supercharger',  network: 'Tesla',             positionMi: 55,  maxKw: 250, pricePerKwh: 0.25 },
      { id: 'inter_ea_a', name: 'Rest Area EA 1',           network: 'Electrify America', positionMi: 110, maxKw: 350, pricePerKwh: 0.27 },
      { id: 'inter_ea_b', name: 'Rest Area EA 2',           network: 'Electrify America', positionMi: 165, maxKw: 350, pricePerKwh: 0.27 },
      { id: 'inter_ev_a', name: 'Midland EVgo',             network: 'EVgo',              positionMi: 195, maxKw: 100, pricePerKwh: 0.31 },
    ],
  },

  // ── Hard ─────────────────────────────────────────────────────────────────────
  {
    id: 'mountain_pass',
    name: 'Mountain Pass',
    description: 'Steep grades test regen efficiency. Trucks and inefficient cars will struggle.',
    distanceMi: 160,
    difficulty: 'Hard',
    reward: 1200,
    unlockAfterTrips: 8,
    terrain: [
      { distanceMi: 0,   elevationFt: 2000, speedLimitMph: 55 },
      { distanceMi: 20,  elevationFt: 4500, speedLimitMph: 45 },
      { distanceMi: 35,  elevationFt: 7200, speedLimitMph: 45 },
      { distanceMi: 50,  elevationFt: 9500, speedLimitMph: 35 },
      { distanceMi: 65,  elevationFt: 11400,speedLimitMph: 35 },
      { distanceMi: 80,  elevationFt: 12000,speedLimitMph: 35 },
      { distanceMi: 95,  elevationFt: 9800, speedLimitMph: 35 },
      { distanceMi: 110, elevationFt: 7000, speedLimitMph: 45 },
      { distanceMi: 130, elevationFt: 4200, speedLimitMph: 55 },
      { distanceMi: 150, elevationFt: 2500, speedLimitMph: 55 },
      { distanceMi: 160, elevationFt: 2000, speedLimitMph: 55 },
    ],
    chargers: [
      { id: 'mtn_sc_a', name: 'Base Camp Supercharger', network: 'Tesla',             positionMi: 18,  maxKw: 250, pricePerKwh: 0.25 },
      { id: 'mtn_ea_a', name: 'Summit EA',               network: 'Electrify America', positionMi: 75,  maxKw: 350, pricePerKwh: 0.29 },
      { id: 'mtn_l2_a', name: 'Ski Resort Level 2',      network: 'ChargePoint',       positionMi: 82,  maxKw: 19.2,pricePerKwh: 0.15 },
      { id: 'mtn_sc_b', name: 'Descent Supercharger',    network: 'Tesla',             positionMi: 120, maxKw: 250, pricePerKwh: 0.25 },
    ],
  },
  {
    id: 'desert_crossing',
    name: 'Desert Crossing',
    description: 'Hot, flat desert with few chargers far apart. Manage range carefully.',
    distanceMi: 280,
    difficulty: 'Hard',
    reward: 1500,
    unlockAfterTrips: 10,
    terrain: [
      { distanceMi: 0,   elevationFt: 1200, speedLimitMph: 75 },
      { distanceMi: 50,  elevationFt: 1000, speedLimitMph: 80 },
      { distanceMi: 100, elevationFt: 800,  speedLimitMph: 80 },
      { distanceMi: 140, elevationFt: 1500, speedLimitMph: 75 },
      { distanceMi: 180, elevationFt: 900,  speedLimitMph: 80 },
      { distanceMi: 220, elevationFt: 700,  speedLimitMph: 80 },
      { distanceMi: 260, elevationFt: 1100, speedLimitMph: 75 },
      { distanceMi: 280, elevationFt: 1300, speedLimitMph: 75 },
    ],
    chargers: [
      { id: 'desert_ea_a', name: 'Desert Oasis EA',    network: 'Electrify America', positionMi: 85,  maxKw: 350, pricePerKwh: 0.27 },
      { id: 'desert_sc_a', name: 'Mirage Supercharger',network: 'Tesla',             positionMi: 170, maxKw: 250, pricePerKwh: 0.25 },
      { id: 'desert_ev_a', name: 'Last Chance EVgo',   network: 'EVgo',              positionMi: 240, maxKw: 100, pricePerKwh: 0.33 },
    ],
  },

  // ── Expert ────────────────────────────────────────────────────────────────────
  {
    id: 'alpine_circuit',
    name: 'Alpine Circuit',
    description: 'Multiple mountain passes back-to-back. Only the most efficient cars finish.',
    distanceMi: 350,
    difficulty: 'Expert',
    reward: 2500,
    unlockAfterTrips: 15,
    terrain: [
      { distanceMi: 0,   elevationFt: 3000, speedLimitMph: 55 },
      { distanceMi: 25,  elevationFt: 7000, speedLimitMph: 45 },
      { distanceMi: 50,  elevationFt: 10500,speedLimitMph: 35 },
      { distanceMi: 70,  elevationFt: 5500, speedLimitMph: 45 },
      { distanceMi: 90,  elevationFt: 2500, speedLimitMph: 55 },
      { distanceMi: 110, elevationFt: 8000, speedLimitMph: 45 },
      { distanceMi: 140, elevationFt: 12500,speedLimitMph: 35 },
      { distanceMi: 170, elevationFt: 6000, speedLimitMph: 45 },
      { distanceMi: 200, elevationFt: 3000, speedLimitMph: 55 },
      { distanceMi: 230, elevationFt: 9000, speedLimitMph: 45 },
      { distanceMi: 260, elevationFt: 13000,speedLimitMph: 35 },
      { distanceMi: 290, elevationFt: 7000, speedLimitMph: 45 },
      { distanceMi: 320, elevationFt: 3500, speedLimitMph: 55 },
      { distanceMi: 350, elevationFt: 3000, speedLimitMph: 55 },
    ],
    chargers: [
      { id: 'alpine_sc_a', name: 'Pass 1 Supercharger',  network: 'Tesla',             positionMi: 40,  maxKw: 250, pricePerKwh: 0.25 },
      { id: 'alpine_ea_a', name: 'Summit A – EA',         network: 'Electrify America', positionMi: 85,  maxKw: 350, pricePerKwh: 0.30 },
      { id: 'alpine_sc_b', name: 'Pass 2 Supercharger',  network: 'Tesla',             positionMi: 130, maxKw: 250, pricePerKwh: 0.25 },
      { id: 'alpine_ea_b', name: 'Summit B – EA',         network: 'Electrify America', positionMi: 185, maxKw: 350, pricePerKwh: 0.30 },
      { id: 'alpine_sc_c', name: 'Pass 3 Supercharger',  network: 'Tesla',             positionMi: 245, maxKw: 250, pricePerKwh: 0.25 },
      { id: 'alpine_ea_c', name: 'Summit C – EA',         network: 'Electrify America', positionMi: 295, maxKw: 350, pricePerKwh: 0.30 },
    ],
  },
  {
    id: 'cross_country',
    name: 'Cross-Country Sprint',
    description: 'The ultimate challenge: coast to coast, all terrain types, maximum distance.',
    distanceMi: 600,
    difficulty: 'Expert',
    reward: 5000,
    unlockAfterTrips: 20,
    terrain: [
      { distanceMi: 0,   elevationFt: 50,   speedLimitMph: 65 },
      { distanceMi: 60,  elevationFt: 800,  speedLimitMph: 70 },
      { distanceMi: 120, elevationFt: 3000, speedLimitMph: 65 },
      { distanceMi: 160, elevationFt: 8000, speedLimitMph: 45 },
      { distanceMi: 200, elevationFt: 5000, speedLimitMph: 55 },
      { distanceMi: 240, elevationFt: 2000, speedLimitMph: 70 },
      { distanceMi: 300, elevationFt: 1000, speedLimitMph: 80 },
      { distanceMi: 360, elevationFt: 700,  speedLimitMph: 80 },
      { distanceMi: 400, elevationFt: 4000, speedLimitMph: 65 },
      { distanceMi: 440, elevationFt: 9500, speedLimitMph: 45 },
      { distanceMi: 480, elevationFt: 3000, speedLimitMph: 65 },
      { distanceMi: 530, elevationFt: 500,  speedLimitMph: 75 },
      { distanceMi: 580, elevationFt: 200,  speedLimitMph: 65 },
      { distanceMi: 600, elevationFt: 10,   speedLimitMph: 55 },
    ],
    chargers: [
      { id: 'cc_sc_a', name: 'Atlantic Supercharger',  network: 'Tesla',             positionMi: 80,  maxKw: 250, pricePerKwh: 0.25 },
      { id: 'cc_ea_a', name: 'Appalachian EA',          network: 'Electrify America', positionMi: 150, maxKw: 350, pricePerKwh: 0.27 },
      { id: 'cc_sc_b', name: 'Heartland Supercharger', network: 'Tesla',             positionMi: 230, maxKw: 250, pricePerKwh: 0.25 },
      { id: 'cc_ea_b', name: 'Plains EA',               network: 'Electrify America', positionMi: 310, maxKw: 350, pricePerKwh: 0.27 },
      { id: 'cc_ev_a', name: 'Desert EVgo',             network: 'EVgo',              positionMi: 390, maxKw: 100, pricePerKwh: 0.31 },
      { id: 'cc_sc_c', name: 'Rockies Supercharger',   network: 'Tesla',             positionMi: 455, maxKw: 250, pricePerKwh: 0.25 },
      { id: 'cc_ea_c', name: 'Sierra EA',               network: 'Electrify America', positionMi: 520, maxKw: 350, pricePerKwh: 0.27 },
      { id: 'cc_sc_d', name: 'Pacific Supercharger',   network: 'Tesla',             positionMi: 575, maxKw: 250, pricePerKwh: 0.25 },
    ],
  },
];

export const ROUTE_MAP: Record<string, Route> = Object.fromEntries(
  ROUTES.map(r => [r.id, r])
);

export function getRoute(id: string): Route {
  return ROUTE_MAP[id] ?? ROUTES[0];
}
